Update build.sh
dsx1123/telemetry_collector pull request #12
Opened 2024-02-18 14:37 UTC by jakethesnak3

2024-02-18 14:38 UTC, jakethesnak3 commented
Typo which breaks the build

2024-02-22 05:17 UTC, dsx1123 requested changes

2024-02-22 05:17 UTC, dsx1123 commented on build.sh
> +    for a in ${switches[@]}; do
thank you! I just realized lines 181-183 are actually for the debugging, these lines should be removed. do you mind removing them, I will merge the request.

2024-05-20 17:20 UTC, dsx1123 commented
addressed in https://github.com/dsx1123/telemetry_collector/commit/b09a5bc9895630eded886b3eee1520aaab7f48f8

2024-05-20 17:20 UTC, closed without merging